import { RouteDefinition, UpstreamService, RateLimitTier, GatewayKpiStats } from "./types";

export const defaultGatewayKpis: GatewayKpiStats = {
  engineName: "Tyk / Envoy Proxy",
  podsCount: "6/6 Pods Healthy",
  ingressRps: 3420,
  p99Latency: "1.4 ms",
  errorRate: 0.04,
  errorBreakdown: "4xx: 0.03% | 5xx: 0.01%",
  slaPercent: 99.995,
  monthlyBudgetRemaining: "2.1m remaining",
};

export const defaultRoutes: RouteDefinition[] = [
  {
    id: "rt-01",
    path: "/v1/telemetry/ingest",
    method: "POST",
    upstream: "telemetry-ingest.soc.svc.cluster.local:8080",
    authType: "mTLS",
    rateLimit: 60000,
    status: "ACTIVE",
    category: "Telemetry",
    middleware: ["mTLS-Validator", "Payload-Decompressor", "Kafka-Forwarder", "Rate-Limiter-Tier1"],
  },
  {
    id: "rt-02",
    path: "/v1/fleet/control/emergency-stop",
    method: "POST",
    upstream: "fleet-control.soc.svc.cluster.local:9090",
    authType: "OIDC_JWT",
    rateLimit: 120,
    status: "ACTIVE",
    category: "Fleet Control",
    middleware: ["OIDC-Token-Validator", "ABAC-Emergency-Guard", "KMS-Audit-Signer", "High-Priority-Queue"],
  },
  {
    id: "rt-03",
    path: "/v1/ota/campaigns/dispatch",
    method: "POST",
    upstream: "ota-manager.soc.svc.cluster.local:8081",
    authType: "OIDC_JWT",
    rateLimit: 300,
    status: "ACTIVE",
    category: "OTA",
    middleware: ["OAuth-Scope-Checker", "Binary-Hash-Verify", "Audit-Logger"],
  },
  {
    id: "rt-04",
    path: "/v1/fleet/vehicles",
    method: "GET",
    upstream: "fleet-control.soc.svc.cluster.local:9090",
    authType: "OIDC_JWT",
    rateLimit: 5000,
    status: "ACTIVE",
    category: "Fleet Control",
    middleware: ["JWT-Auth", "Response-Cache-TTL-3s", "Compress-Gzip"],
  },
  {
    id: "rt-05",
    path: "/v1/can-bus/stream",
    method: "gRPC",
    upstream: "can-bridge.telematics.svc.cluster.local:50051",
    authType: "mTLS",
    rateLimit: 120000,
    status: "DEGRADED",
    category: "Telemetry",
    middleware: ["mTLS-Verify", "CAN-Frame-Filter", "WSS-Tunnel"],
  },
  {
    id: "rt-06",
    path: "/v1/partner/traffic-advisory",
    method: "POST",
    upstream: "v2x-ext-relay.partner.svc.cluster.local:8443",
    authType: "API_KEY",
    rateLimit: 600,
    status: "MAINTENANCE",
    category: "Partner",
    middleware: ["API-Key-Validator", "Circuit-Breaker-Trip-Guard", "SLA-Quota-Tracker"],
  },
];

export const defaultUpstreams: UpstreamService[] = [
  {
    id: "up-telemetry",
    name: "telemetry-ingest-v2",
    k8sService: "telemetry-ingest.soc.svc.cluster.local:8080",
    pods: 12,
    latencyP95: "4.2 ms",
    errorRate: "0.01%",
    circuitState: "CLOSED",
    health: 99.99,
  },
  {
    id: "up-fleet-ctrl",
    name: "fleet-coordinator-core",
    k8sService: "fleet-control.soc.svc.cluster.local:9090",
    pods: 8,
    latencyP95: "16.8 ms",
    errorRate: "0.03%",
    circuitState: "CLOSED",
    health: 99.96,
  },
  {
    id: "up-iam-engine",
    name: "auth-identity-provider",
    k8sService: "iam-core.auth.svc.cluster.local:443",
    pods: 6,
    latencyP95: "8.1 ms",
    errorRate: "0.00%",
    circuitState: "CLOSED",
    health: 100.0,
  },
  {
    id: "up-can-stream",
    name: "can-bus-grpc-bridge",
    k8sService: "can-bridge.telematics.svc.cluster.local:50051",
    pods: 4,
    latencyP95: "74.5 ms",
    errorRate: "3.40%",
    circuitState: "HALF_OPEN",
    health: 96.6,
  },
  {
    id: "up-partner-v2x",
    name: "seoul-smartcity-v2x-relay",
    k8sService: "v2x-ext-relay.partner.svc.cluster.local:8443",
    pods: 2,
    latencyP95: "210.0 ms",
    errorRate: "42.10%",
    circuitState: "OPEN",
    health: 57.9,
  },
];

export const defaultRateTiers: RateLimitTier[] = [
  {
    id: "tier-fleet",
    name: "Autonomous Vehicle Fleet (mTLS)",
    limitRpm: 60000,
    burst: 5000,
    algorithm: "Token Bucket (Redis)",
    activeClients: 150,
  },
  {
    id: "tier-soc",
    name: "SOC Operator Dashboard (OIDC)",
    limitRpm: 10000,
    burst: 800,
    algorithm: "Sliding Window Log",
    activeClients: 24,
  },
  {
    id: "tier-partner",
    name: "External City V2X Partner (API Key)",
    limitRpm: 1200,
    burst: 100,
    algorithm: "Leaky Bucket",
    activeClients: 5,
  },
  {
    id: "tier-public",
    name: "Public Telematics Ingress",
    limitRpm: 300,
    burst: 20,
    algorithm: "Fixed Window Counter",
    activeClients: 1200,
  },
];
