"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ko";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ConsoleLayout
    "nav.dashboard": "Dashboard",
    "nav.gateway": "API Gateway (Tyk)",
    "nav.iam": "IAM & OAuth 2.0",
    "nav.incidents": "Incidents & Alerts",
    "nav.fleet": "Fleet & Devices",
    "nav.audit": "Audit Trail",
    "nav.settings": "System & ABAC",
    "layout.title": "COREGUARD SOC",
    "layout.subtitle": "42dot Safety Unit",
    "layout.threat": "THREAT STATUS:",
    "layout.threat.normal": "NORMAL",
    "layout.threat.elevated": "ELEVATED",
    "layout.threat.critical": "CRITICAL",
    "layout.latency": "V2X LATENCY:",
    "layout.gps": "GPS LINK:",
    "layout.gps_active": "ACTIVE",
    "layout.reset_soc": "RESET SOC",
    "layout.test_panic": "TEST PANIC",
    "layout.emergency": "CRITICAL SYSTEM EMERGENCY OVERRIDE: GLOBAL SAFE-STOP PROTOCOLS ENGAGED",
    "layout.timeline": "SYSTEM TIMELINE:",
    "layout.timeline_panic": "!!! ALERT: EMER EMERGENCY SHUTDOWN SENT TO ALL VEHS !!!",
    "layout.timeline_normal": "Telemetry check complete: 148 vehicles responding, 2 in hangar sleep state.",
    "layout.cloud_link": "COREGUARD CLOUD LINK:",
    "layout.cloud_secure": "SECURE",
    "layout.api_status": "API SERVICE STATUS:",
    "layout.db_cluster": "DB CLUSTER:",
    "layout.db_replicated": "REPLICATED",
    "layout.ver": "VER:",
    "layout.region.seoul": "Seoul - Gangnam",
    "layout.region.pangyo": "Seoul - Pangyo",
    "layout.region.california": "California - Cupertino",
    
    // DashboardView
    "dashboard.score": "Fleet Safety Score",
    "dashboard.alerts": "Active Alerts",
    "dashboard.latency": "V2X Core Latency",
    "dashboard.fleet_service": "Fleet In Service",
    "dashboard.standby": "Standby:",
    "dashboard.hangar": "2 in hangar depot",
    "dashboard.unresolved": "Unresolved anomalies:",
    "dashboard.critical": "Critical",
    "dashboard.telemetry_rate": "99.98% telemetry frame rate",
    "dashboard.vs_last_hour": "vs last hour",
    "dashboard.map_title": "Active Threat Level Status Map",
    "dashboard.map_subtitle": "Interactive Fleet Telemetry Monitor",
    "dashboard.diag_title": "Selected Vehicle Diagnostic Node",
    "dashboard.diag_placeholder": "No vehicle selected on map node. Click any node pulse above to bind telemetry feed.",
    "dashboard.diag_report": "VEHICLE STATUS REPORT",
    "dashboard.diag_v2x": "V2X LINK STRENGTH",
    "dashboard.diag_hw": "HARDWARE INTEGRITY",
    "dashboard.diag_fw": "FIRMWARE VER",
    "dashboard.diag_speed": "SPEED OVERRIDE LIMIT",
    "dashboard.diag_gps": "GPS POSITION",
    "dashboard.diag_decom_proto": "DECOMMISSION PROTOCOL",
    "dashboard.diag_decom_btn": "DECOMMISSION VEHICLE",
    "dashboard.diag_normal": "All systems reporting normal telemetry parameters.",
    "dashboard.diag_anomalous": "ANOMALOUS OVERRIDES DETECTED",
    "dashboard.map_header": "GANGNAM REGION AUTOMATED GEOLOCATOR",
    "dashboard.map.secure_objects": "SECURE OBJECTS",
    "dashboard.map.warning_overrides": "WARNING OVERRIDES",
    "dashboard.map.emergency_tripped": "EMERGENCY TRIPPED",
    "dashboard.map.critical_tamper": "CRITICAL TAMPER",
    "dashboard.lidar_header": "LIDAR TELEMETRY FRAMERATE",
    "dashboard.trend_12h": "12H TREND",
    "dashboard.anomalous_drop": "Anomalous Drop",
    "dashboard.packet_success": "Packet Success",
    "dashboard.can_rate": "CAN Message Rate",
    "dashboard.incidents_queue": "Active Incidents Queue",
    "dashboard.investigate_all": "INVESTIGATE ALL",
    "dashboard.zero_active": "Zero active safety incidents reported.",
    "dashboard.live_audit": "Live Audit Ticker",
    "dashboard.explore_logs": "EXPLORE LOGS",
    
    // IncidentsView
    "incidents.search": "Search by incident ID, vehicle ID, anomaly...",
    "incidents.severity": "Severity:",
    "incidents.status": "Status:",
    "incidents.all": "ALL",
    "incidents.critical_sev": "CRITICAL",
    "incidents.high_sev": "HIGH",
    "incidents.medium_sev": "MEDIUM",
    "incidents.info_sev": "INFO",
    "incidents.active_stat": "ACTIVE",
    "incidents.triaged_stat": "TRIAGED",
    "incidents.resolved_stat": "RESOLVED",
    "incidents.action_triage": "Mark Triaged",
    "incidents.action_resolve": "Resolve Incident",
    "incidents.action_reactivate": "Reactivate Alert",
    "incidents.notes_label": "SOC Investigator Action Notes",
    "incidents.notes_placeholder": "Enter mitigation steps taken, dispatcher observations, or containment confirmation...",
    "incidents.notes_save": "SAVE INVESTIGATION LOG",
    "incidents.notes_saved": "Investigation notes logged successfully.",
    "incidents.can_bus": "Real-time Vehicle CAN Bus Stream",
    "incidents.can_desc": "Sub-can boundary tap (Active monitor)",
    "incidents.can_col_id": "FRAME ID",
    "incidents.can_col_dlc": "DLC",
    "incidents.can_col_data": "DATA PAYLOAD (HEX)",
    "incidents.can_col_desc": "DIAGNOSTIC RESOLUTION",
    
    // FleetView
    "fleet.search": "Search fleet by ID or coordinates/location...",
    "fleet.type_all": "ALL",
    "fleet.col_id": "VEHICLE ID",
    "fleet.col_type": "TYPE",
    "fleet.col_status": "SECURITY STATUS",
    "fleet.col_battery": "BATTERY",
    "fleet.col_speed": "TELEMETRY SPEED",
    "fleet.col_sensors": "SENSORS INTEGRITY",
    "fleet.col_actions": "OVERRIDE ACTIONS",
    "fleet.edit_speed": "Override Max Speed",
    "fleet.edit_loc": "Update Coordinates",
    "fleet.decom": "Decommission",
    "fleet.sensors_ok": "SECURE",
    "fleet.sensors_deg": "DEGRADED",
    "fleet.sensors_off": "OFFLINE",
    "fleet.panel_details": "Vehicle Operational Details",
    "fleet.panel_placeholder": "Select a vehicle from the fleet to view sensors telemetry & active overrides.",
    "fleet.firmware": "Firmware Version",
    "fleet.last_reported": "Last Reported Location",
    "fleet.speed_limit": "Active Speed Limit Override",
    
    // AuditView
    "audit.search": "Search audit trail by operator, action code, or ID...",
    "audit.export": "EXPORT CSV",
    "audit.title": "KMS-Secured Immutable Audit Trail",
    "audit.subtitle": "SHA-256 CRYPTO-VALIDATED",
    "audit.col_id": "LOG ID",
    "audit.col_time": "TIMESTAMP",
    "audit.col_level": "LEVEL",
    "audit.col_actor": "ACTOR / NODE",
    "audit.col_action": "ACTION DETAILS",
    "audit.col_source": "IP / ROUTE",
    "audit.col_hash": "CRYPTO HASH (SHA-256)",
    
    // SettingsView
    "settings.tab_rbac": "Role-Based Access (RBAC)",
    "settings.tab_safety": "Safety & Overrides",
    "settings.tab_api": "API Auth Credentials",
    "settings.tab_alerts": "Alert Thresholds",
    "settings.rbac_title": "SOC Role Permission Matrix",
    "settings.rbac_subtitle": "Assign active protocol capability privileges across personnel classifications.",
    "settings.rbac_col_permission": "OPERATION / ACTION CODE",
    "settings.rbac_col_admin": "SOC ADMIN",
    "settings.rbac_col_disp": "DISPATCHER",
    "settings.rbac_col_analyst": "ANALYST",
    "settings.rbac_col_tech": "FIELD TECH",
    "settings.safety_title": "Autonomous Fleet Safety Overrides",
    "settings.safety_subtitle": "Configure active safety parameters, manual takeover conditions, and emergency brake locks.",
    "settings.api_title": "Autonomous Ingestion Auth Credentials",
    "settings.api_subtitle": "Generate and manage cryptographically signed access tokens for fleet telemetry gateways.",
    "settings.api_col_name": "KEY CLASSIFICATION",
    "settings.api_col_created": "CREATED ON",
    "settings.api_col_type": "ROLE CLASS",
    "settings.api_col_status": "STATUS",
    "settings.api_col_action": "REVOCATION",
    "settings.api_create": "CREATE INGESTION KEY",
    "settings.api_revoke": "REVOKE ACCESS",
    "settings.alerts_title": "Operational Telemetry Alert Thresholds",
    "settings.alerts_subtitle": "Configure threshold values that trigger real-time alerts on the SOC Dashboard.",
    "settings.alerts_bat_warn": "Battery Low Warning Threshold (%)",
    "settings.alerts_bat_crit": "Battery Critical Alert Threshold (%)",
    "settings.alerts_lat_warn": "V2X Latency Warning Threshold (ms)",
    "settings.alerts_lat_crit": "V2X Latency Critical Threshold (ms)",
    "settings.alerts_lidar_warn": "LiDAR PPS Minimum Warning Rate (pps)",
    "settings.alerts_lidar_crit": "LiDAR PPS Critical Failure Rate (pps)",
    "settings.tab_policies": "Policies & Geozones",
    "policies.create": "Create New Policy",
    "policies.edit": "Edit Policy",
    "policies.list_title": "Active Geofence Policies",
    "policies.name_label": "Policy Name",
    "policies.name_placeholder": "e.g., Teheran-ro Delivery Bounds",
    "policies.action_label": "Violation Action Rule",
    "policies.action_raise": "ACT_RAISE_INCIDENT (Flag Security Threat)",
    "policies.action_stop": "ACT_FORCE_STOP (Remote Safe-Stop Protocol)",
    "policies.action_limit": "ACT_LIMIT_SPEED (Governor Cap to 20 km/h)",
    "policies.action_warn": "ACT_WARN_DRIVER (Warning Dispatch Audio)",
    "policies.vehicles_label": "Apply to Fleet Vehicles",
    "policies.map_instructions": "GIS Map Editor: Click to place geofence vertices. Click first vertex or double-click to close polygon.",
    "policies.draw_start": "Start Drawing",
    "policies.draw_clear": "Clear Coordinates",
    "policies.save": "Save Policy & Deploy",
    "policies.cancel": "Cancel Editor",
    "policies.status_active": "DEPLOYED",
    "policies.violations": "Violations",
    "policies.no_points": "No geofence coordinates mapped yet.",
    "policies.points_drawn": "vertices mapped",
    "policies.all_vehicles": "Select All",
    "policies.none_vehicles": "Deselect All",
  },
  ko: {
    // ConsoleLayout
    "nav.dashboard": "대시보드",
    "nav.gateway": "API 게이트웨이 (Tyk)",
    "nav.iam": "IAM 및 OAuth 2.0",
    "nav.incidents": "인시던트 및 알림",
    "nav.fleet": "플릿 및 디바이스",
    "nav.audit": "감사 추적",
    "nav.settings": "시스템 및 ABAC",
    "layout.title": "코어가드 SOC",
    "layout.subtitle": "42dot 안전 부서",
    "layout.threat": "위협 상태:",
    "layout.threat.normal": "정상",
    "layout.threat.elevated": "주의",
    "layout.threat.critical": "경계",
    "layout.latency": "V2X 지연 시간:",
    "layout.gps": "GPS 연결:",
    "layout.gps_active": "활성",
    "layout.reset_soc": "SOC 리셋",
    "layout.test_panic": "테스트 패닉",
    "layout.emergency": "중요 시스템 비상 무력화: 글로벌 안전 정지 프로토콜 가동됨",
    "layout.timeline": "시스템 타임라인:",
    "layout.timeline_panic": "!!! 경고: 모든 차량에 비상 정지 명령 전송됨 !!!",
    "layout.timeline_normal": "텔레메트리 체크 완료: 148대 차량 응답 중, 2대 격납고 대기 모드.",
    "layout.cloud_link": "코어가드 클라우드 연결:",
    "layout.cloud_secure": "보안 연결됨",
    "layout.api_status": "API 서비스 상태:",
    "layout.db_cluster": "DB 클러스터:",
    "layout.db_replicated": "복제 완료",
    "layout.ver": "버전:",
    "layout.region.seoul": "서울 - 강남",
    "layout.region.pangyo": "서울 - 판교",
    "layout.region.california": "캘리포니아 - 쿠퍼티노",
    
    // DashboardView
    "dashboard.score": "플릿 안전 점수",
    "dashboard.alerts": "활성 알림",
    "dashboard.latency": "V2X 코어 지연 시간",
    "dashboard.fleet_service": "운행 중인 플릿",
    "dashboard.standby": "대기 중:",
    "dashboard.hangar": "2대 격납고 대기",
    "dashboard.unresolved": "미해결 이상 현상:",
    "dashboard.critical": "임계",
    "dashboard.telemetry_rate": "99.98% 텔레메트리 프레임 속도",
    "dashboard.vs_last_hour": "지난 시간 대비",
    "dashboard.map_title": "활성 위협 수준 상태 지도",
    "dashboard.map_subtitle": "대화형 플릿 텔레메트리 모니터",
    "dashboard.diag_title": "선택된 차량 진단 노드",
    "dashboard.diag_placeholder": "지도 노드에서 선택된 차량이 없습니다. 위 노드 펄스를 클릭하여 텔레메트리 피드를 연결하세요.",
    "dashboard.diag_report": "차량 상태 보고서",
    "dashboard.diag_v2x": "V2X 링크 강도",
    "dashboard.diag_hw": "하드웨어 무결성",
    "dashboard.diag_fw": "펌웨어 버전",
    "dashboard.diag_speed": "속도 오버라이드 제한",
    "dashboard.diag_gps": "GPS 위치",
    "dashboard.diag_decom_proto": "폐기 프로토콜",
    "dashboard.diag_decom_btn": "차량 폐기",
    "dashboard.diag_normal": "모든 시스템이 정상 텔레메트리 매개변수를 보고하고 있습니다.",
    "dashboard.diag_anomalous": "이상 오버라이드 탐지됨",
    "dashboard.map_header": "강남 지역 자동 지오로케이터",
    "dashboard.map.secure_objects": "보안 연결됨",
    "dashboard.map.warning_overrides": "경고 오버라이드",
    "dashboard.map.emergency_tripped": "비상 정지 작동됨",
    "dashboard.map.critical_tamper": "중요 무단 변경",
    "dashboard.lidar_header": "LIDAR 텔레메트리 프레임 속도",
    "dashboard.trend_12h": "12시간 트렌드",
    "dashboard.anomalous_drop": "이상 하락",
    "dashboard.packet_success": "패킷 성공률",
    "dashboard.can_rate": "CAN 메시지 전송률",
    "dashboard.incidents_queue": "활성 인시던트 대기열",
    "dashboard.investigate_all": "전체 조사",
    "dashboard.zero_active": "활성 안전 인시던트가 보고되지 않았습니다.",
    "dashboard.live_audit": "실시간 감사 티커",
    "dashboard.explore_logs": "로그 탐색",
    
    // IncidentsView
    "incidents.search": "인시던트 ID, 차량 ID, 이상 현상으로 검색...",
    "incidents.severity": "심각도:",
    "incidents.status": "상태:",
    "incidents.all": "전체",
    "incidents.critical_sev": "심각",
    "incidents.high_sev": "높음",
    "incidents.medium_sev": "보통",
    "incidents.info_sev": "정보",
    "incidents.active_stat": "활성",
    "incidents.triaged_stat": "조사중",
    "incidents.resolved_stat": "해결됨",
    "incidents.action_triage": "조사 중으로 표시",
    "incidents.action_resolve": "인시던트 해결",
    "incidents.action_reactivate": "알림 재활성화",
    "incidents.notes_label": "SOC 조사관 조치 사항 메모",
    "incidents.notes_placeholder": "조치 단계, 관제사 의견 또는 격리 확인 사항을 입력하세요...",
    "incidents.notes_save": "조사 로그 저장",
    "incidents.notes_saved": "조사 메모가 성공적으로 로깅되었습니다.",
    "incidents.can_bus": "실시간 차량 CAN 버스 스트림",
    "incidents.can_desc": "하위 CAN 경계 탭 (활성 모니터)",
    "incidents.can_col_id": "프레임 ID",
    "incidents.can_col_dlc": "DLC",
    "incidents.can_col_data": "데이터 페이로드 (HEX)",
    "incidents.can_col_desc": "진단 해상도",
    
    // FleetView
    "fleet.search": "차량 ID 또는 좌표/위치로 검색...",
    "fleet.type_all": "전체",
    "fleet.col_id": "차량 ID",
    "fleet.col_type": "유형",
    "fleet.col_status": "보안 상태",
    "fleet.col_battery": "배터리",
    "fleet.col_speed": "텔레메트리 속도",
    "fleet.col_sensors": "센서 무결성",
    "fleet.col_actions": "오버라이드 조치",
    "fleet.edit_speed": "최대 속도 오버라이드",
    "fleet.edit_loc": "좌표 업데이트",
    "fleet.decom": "폐기",
    "fleet.sensors_ok": "안전함",
    "fleet.sensors_deg": "성능 저하",
    "fleet.sensors_off": "오프라인",
    "fleet.panel_details": "차량 운행 세부 정보",
    "fleet.panel_placeholder": "플릿에서 차량을 선택하여 센서 텔레메트리 및 활성 오버라이드를 확인하세요.",
    "fleet.firmware": "펌웨어 버전",
    "fleet.last_reported": "마지막 보고된 위치",
    "fleet.speed_limit": "활성 속도 제어 오버라이드",
    
    // AuditView
    "audit.search": "운영자, 조치 코드 또는 ID로 감사 추적 검색...",
    "audit.export": "CSV 내보내기",
    "audit.title": "KMS 보안 불변 감사 추적",
    "audit.subtitle": "SHA-256 암호화 검증됨",
    "audit.col_id": "로그 ID",
    "audit.col_time": "타임스탬프",
    "audit.col_level": "등급",
    "audit.col_actor": "운영자 / 노드",
    "audit.col_action": "조치 상세 정보",
    "audit.col_source": "IP / 경로",
    "audit.col_hash": "암호화 해시 (SHA-256)",
    
    // SettingsView
    "settings.tab_rbac": "역할 기반 액세스 (RBAC)",
    "settings.tab_safety": "안전 및 오버라이드",
    "settings.tab_api": "API 인증 자격 증명",
    "settings.tab_alerts": "경고 기준값",
    "settings.rbac_title": "SOC 역할 권한 매트릭스",
    "settings.rbac_subtitle": "인력 등급별로 활성 프로토콜 기능 권한을 할당합니다.",
    "settings.rbac_col_permission": "작업 / 조치 코드",
    "settings.rbac_col_admin": "SOC 관리자",
    "settings.rbac_col_disp": "디스패처",
    "settings.rbac_col_analyst": "분석가",
    "settings.rbac_col_tech": "현장 기술자",
    "settings.safety_title": "자율 주행 플릿 안전 오버라이드",
    "settings.safety_subtitle": "활성 안전 매개변수, 수동 제어 인계 조건 및 비상 브레이크 잠금을 설정합니다.",
    "settings.api_title": "자율 주행 데이터 수집 자격 증명",
    "settings.api_subtitle": "플릿 텔레메트리 게이트웨이용 암호 서명 액세스 토큰을 생성하고 관리합니다.",
    "settings.api_col_name": "키 분류",
    "settings.api_col_created": "생성 날짜",
    "settings.api_col_type": "역할 등급",
    "settings.api_col_status": "상태",
    "settings.api_col_action": "철회",
    "settings.api_create": "수집 키 생성",
    "settings.api_revoke": "액세스 철회",
    "settings.alerts_title": "운행 텔레메트리 경고 임계값",
    "settings.alerts_subtitle": "SOC 대시보드에서 실시간 경고를 트리거할 임계값을 설정합니다.",
    "settings.alerts_bat_warn": "배터리 부족 경고 임계값 (%)",
    "settings.alerts_bat_crit": "배터리 위험 알림 임계값 (%)",
    "settings.alerts_lat_warn": "V2X 지연 시간 경고 임계값 (ms)",
    "settings.alerts_lat_crit": "V2X 지연 시간 위험 임계값 (ms)",
    "settings.alerts_lidar_warn": "LiDAR PPS 최소 경고 속도 (pps)",
    "settings.alerts_lidar_crit": "LiDAR PPS 중요 임계 속도 (pps)",
    "settings.tab_policies": "정책 및 지오존 관리",
    "policies.create": "새 정책 생성",
    "policies.edit": "정책 편집",
    "policies.list_title": "활성 지오펜스 정책 목록",
    "policies.name_label": "정책 이름",
    "policies.name_placeholder": "예: 테헤ран로 배송 구역",
    "policies.action_label": "위반 시 조치 규칙",
    "policies.action_raise": "ACT_RAISE_INCIDENT (보안 위협 경го)",
    "policies.action_stop": "ACT_FORCE_STOP (원격 안전 정지 가동)",
    "policies.action_limit": "ACT_LIMIT_SPEED (최대 속도 20km/h 제한)",
    "policies.action_warn": "ACT_WARN_DRIVER (디스패처 경고음 송출)",
    "policies.vehicles_label": "적용할 플릿 차량 선택",
    "policies.map_instructions": "GIS 맵 에디터: 클릭하여 지오펜스 정점을 배치하세요. 첫 번째 점을 클릭하거나 더블 클릭하여 폴리곤을 닫습니다.",
    "policies.draw_start": "그리기 시작",
    "policies.draw_clear": "좌표 초기화",
    "policies.save": "정책 저장 및 배포",
    "policies.cancel": "에디터 취소",
    "policies.status_active": "배포 완료",
    "policies.violations": "위반 발생",
    "policies.no_points": "아직 배치된 지오펜스 좌표가 없습니다.",
    "policies.points_drawn": "개 정점 배치됨",
    "policies.all_vehicles": "전체 선택",
    "policies.none_vehicles": "선택 해제",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  // Load language from localStorage if available
  useEffect(() => {
    const savedLang = localStorage.getItem("cg_lang") as Language;
    if (savedLang === "en" || savedLang === "ko") {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("cg_lang", lang);
  };

  const t = (key: string): string => {
    const activeDict = translations[language] || translations.en;
    return activeDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
