import { ThresholdRule, MetricDefinition } from "./types";

export const defaultMetricDefinitions: MetricDefinition[] = [
  {
    key: "battery",
    name: "Vehicle Battery Margin",
    unit: "%",
    min: 5,
    max: 60,
    step: 1,
    warnKey: "batteryWarn",
    critKey: "batteryCrit",
    invertCrit: true, // <15% is worse than <30%
  },
  {
    key: "latency",
    name: "V2X RTT Network Latency",
    unit: "ms",
    min: 20,
    max: 400,
    step: 5,
    warnKey: "latencyWarn",
    critKey: "latencyCrit",
    invertCrit: false, // >200ms is worse than >100ms
  },
  {
    key: "lidar",
    name: "LiDAR Ingest Point Stream",
    unit: "k pts/s",
    min: 50,
    max: 600,
    step: 10,
    warnKey: "lidarPpsWarn",
    critKey: "lidarPpsCrit",
    invertCrit: true, // <200k is worse than <400k
  },
  {
    key: "speed",
    name: "Velocity Speed Cap",
    unit: "km/h",
    min: 20,
    max: 120,
    step: 5,
    warnKey: "speedWarn",
    critKey: "speedCrit",
    invertCrit: false,
  },
  {
    key: "canError",
    name: "OBD-CAN Frame Anomaly Rate",
    unit: "err/s",
    min: 1,
    max: 50,
    step: 1,
    warnKey: "canErrorWarn",
    critKey: "canErrorCrit",
    invertCrit: false,
  },
];

export const defaultThresholdRules: ThresholdRule[] = [
  // ==========================================
  // 🟢 CURRENT (Текущие активные настройки)
  // ==========================================
  {
    id: "thr-global",
    name: "CoreGuard Global Baseline",
    description: "Default fallback threshold rules applied across entire fleet unless overridden by vehicle type or policy geofence.",
    scope: "GLOBAL",
    targetId: "GLOBAL",
    targetName: "All Connected Vehicles (Baseline)",
    temporalStatus: "CURRENT",
    version: "v2.1",
    effectiveDate: "2026-09-01",
    changeReason: "Standard Q3 baseline calibration",
    batteryWarn: 30,
    batteryCrit: 15,
    latencyWarn: 100,
    latencyCrit: 200,
    lidarPpsWarn: 400,
    lidarPpsCrit: 200,
    speedWarn: 60,
    speedCrit: 80,
    canErrorWarn: 5,
    canErrorCrit: 15,
    startTime: null,
    endTime: null,
    isActive: true,
    updatedBy: "secops.lead@coreguard.io",
    updatedAt: "2026-09-08 14:20:00",
  },
  {
    id: "thr-veh-robotaxi",
    name: "Robotaxi Passenger Safety Profile",
    description: "Strict passenger-first criteria. Tight V2X latency bounds and immediate low battery failsafe.",
    scope: "VEHICLE_TYPE",
    targetId: "ROBOTAXI",
    targetName: "Robotaxi Autonomous Fleet (L4)",
    temporalStatus: "CURRENT",
    version: "v2.0",
    effectiveDate: "2026-09-05",
    changeReason: "L4 Autonomous commercial rollout parameters",
    batteryWarn: 35,
    batteryCrit: 20,
    latencyWarn: 80,
    latencyCrit: 160,
    lidarPpsWarn: 450,
    lidarPpsCrit: 250,
    speedWarn: 50,
    speedCrit: 70,
    canErrorWarn: 3,
    canErrorCrit: 10,
    startTime: null,
    endTime: null,
    isActive: true,
    updatedBy: "dispatcher.alex@coreguard.io",
    updatedAt: "2026-09-08 16:45:10",
  },
  {
    id: "thr-veh-shuttle",
    name: "Heavy Transit Shuttle Envelope",
    description: "Tailored for higher passenger capacity vehicles. Adjusted braking curves and power margins.",
    scope: "VEHICLE_TYPE",
    targetId: "SHUTTLE",
    targetName: "Autonomous Transit Shuttles",
    temporalStatus: "CURRENT",
    version: "v1.4",
    effectiveDate: "2026-08-20",
    changeReason: "Transit corridor compliance update",
    batteryWarn: 40,
    batteryCrit: 25,
    latencyWarn: 90,
    latencyCrit: 180,
    lidarPpsWarn: 400,
    lidarPpsCrit: 200,
    speedWarn: 40,
    speedCrit: 55,
    canErrorWarn: 4,
    canErrorCrit: 12,
    startTime: "06:00",
    endTime: "23:00",
    isActive: true,
    updatedBy: "fleet.ops@coreguard.io",
    updatedAt: "2026-09-07 09:15:00",
  },
  {
    id: "thr-veh-delivery",
    name: "Last-Mile Delivery Pod Parameters",
    description: "Lightweight cargo pods. Allows broader latency tolerance and optimized energy consumption.",
    scope: "VEHICLE_TYPE",
    targetId: "DELIVERY",
    targetName: "Last-Mile Cargo Pods",
    temporalStatus: "CURRENT",
    version: "v1.2",
    effectiveDate: "2026-08-15",
    changeReason: "Energy optimization curve update",
    batteryWarn: 25,
    batteryCrit: 10,
    latencyWarn: 140,
    latencyCrit: 260,
    lidarPpsWarn: 350,
    lidarPpsCrit: 180,
    speedWarn: 30,
    speedCrit: 45,
    canErrorWarn: 6,
    canErrorCrit: 20,
    startTime: null,
    endTime: null,
    isActive: true,
    updatedBy: "logistics.guard@coreguard.io",
    updatedAt: "2026-09-06 18:00:22",
  },
  {
    id: "thr-pol-1",
    name: "POL-01: Teheran-ro High-Density Bounds",
    description: "Applied to vehicles operating within Teheran-ro delivery zone. Heavy pedestrian traffic mandates low speed limit.",
    scope: "POLICY",
    targetId: "pol-1",
    targetName: "Teheran-ro Delivery Bounds",
    temporalStatus: "CURRENT",
    version: "v1.3",
    effectiveDate: "2026-09-01",
    changeReason: "Pedestrian zone safety enforcement",
    batteryWarn: 30,
    batteryCrit: 15,
    latencyWarn: 110,
    latencyCrit: 220,
    lidarPpsWarn: 480,
    lidarPpsCrit: 300,
    speedWarn: 35,
    speedCrit: 45,
    canErrorWarn: 4,
    canErrorCrit: 10,
    startTime: "08:00",
    endTime: "20:00",
    isActive: true,
    updatedBy: "safety.commission@seoul.kr",
    updatedAt: "2026-09-08 11:30:00",
  },

  // ==========================================
  // 🔵 FUTURE (Будущие запланированные настройки)
  // ==========================================
  {
    id: "thr-future-night",
    name: "Night Transit Protocol (Low-Traffic)",
    description: "Scheduled nocturnal profile. Decreased traffic enables higher transit velocity while enforcing stricter battery reserve.",
    scope: "GLOBAL",
    targetId: "GLOBAL",
    targetName: "All Connected Vehicles (Nocturnal)",
    temporalStatus: "FUTURE",
    version: "v2.2-NIGHT",
    effectiveDate: "2026-09-10",
    changeReason: "Nighttime automated transit schedule",
    batteryWarn: 35,
    batteryCrit: 20,
    latencyWarn: 70,
    latencyCrit: 140,
    lidarPpsWarn: 420,
    lidarPpsCrit: 220,
    speedWarn: 70,
    speedCrit: 90,
    canErrorWarn: 4,
    canErrorCrit: 12,
    startTime: "23:00",
    endTime: "05:30",
    isActive: true,
    updatedBy: "scheduler@coreguard.io",
    updatedAt: "2026-09-09 02:00:00",
  },
  {
    id: "thr-future-monsoon",
    name: "Monsoon Heavy Rain Sensor Envelope",
    description: "Scheduled for incoming Typhoon advisory. Compensates for wet pavement braking distance and rainwater LiDAR scattering.",
    scope: "POLICY",
    targetId: "pol-2",
    targetName: "Gangnam Speed Patrol (Rain Preset)",
    temporalStatus: "FUTURE",
    version: "v3.0-STORM",
    effectiveDate: "2026-09-11",
    changeReason: "Weather radar forecast: 50mm/hr precipitation expected",
    batteryWarn: 40,
    batteryCrit: 25,
    latencyWarn: 120,
    latencyCrit: 220,
    lidarPpsWarn: 320,
    lidarPpsCrit: 160,
    speedWarn: 30,
    speedCrit: 40,
    canErrorWarn: 5,
    canErrorCrit: 15,
    startTime: "06:00",
    endTime: "18:00",
    isActive: true,
    updatedBy: "weather.ops@kma.go.kr",
    updatedAt: "2026-09-09 08:30:00",
  },

  // ==========================================
  // ⚪ HISTORICAL (Архивные / Прошлые версии)
  // ==========================================
  {
    id: "thr-hist-global-v1",
    name: "CoreGuard Global Baseline (v1.0 Archived)",
    description: "Initial production deployment threshold profile. Superseded following Q2 safety review.",
    scope: "GLOBAL",
    targetId: "GLOBAL",
    targetName: "All Connected Vehicles (v1.0 Archive)",
    temporalStatus: "HISTORICAL",
    version: "v1.0",
    effectiveDate: "2026-05-01 - 2026-08-31",
    changeReason: "Initial fleet rollout profile (deprecated)",
    batteryWarn: 25,
    batteryCrit: 10,
    latencyWarn: 120,
    latencyCrit: 250,
    lidarPpsWarn: 350,
    lidarPpsCrit: 150,
    speedWarn: 50,
    speedCrit: 70,
    canErrorWarn: 8,
    canErrorCrit: 20,
    startTime: null,
    endTime: null,
    isActive: false,
    updatedBy: "architect@coreguard.io",
    updatedAt: "2026-05-01 10:00:00",
  },
  {
    id: "thr-hist-heatwave",
    name: "Summer Heatwave Battery Mitigation (Archived)",
    description: "Temporary summer profile for ambient temperatures > 36°C. Throttled fast discharge rates.",
    scope: "VEHICLE_TYPE",
    targetId: "ROBOTAXI",
    targetName: "Robotaxi Fleet (Heatwave Override)",
    temporalStatus: "HISTORICAL",
    version: "v1.9-HEAT",
    effectiveDate: "2026-07-20 - 2026-08-10",
    changeReason: "Heatwave safety alert expired",
    batteryWarn: 40,
    batteryCrit: 25,
    latencyWarn: 80,
    latencyCrit: 160,
    lidarPpsWarn: 450,
    lidarPpsCrit: 250,
    speedWarn: 45,
    speedCrit: 60,
    canErrorWarn: 3,
    canErrorCrit: 10,
    startTime: null,
    endTime: null,
    isActive: false,
    updatedBy: "battery.engineer@coreguard.io",
    updatedAt: "2026-07-20 11:00:00",
  },
  {
    id: "thr-hist-beta",
    name: "Gangnam Station Pilot Beta (Archived)",
    description: "Trial evaluation thresholds used during initial Gangnam autonomous station testing.",
    scope: "POLICY",
    targetId: "pol-1",
    targetName: "Gangnam Pilot Corridor",
    temporalStatus: "HISTORICAL",
    version: "v0.9-BETA",
    effectiveDate: "2026-03-01 - 2026-06-01",
    changeReason: "Pilot phase concluded successfully",
    batteryWarn: 35,
    batteryCrit: 20,
    latencyWarn: 150,
    latencyCrit: 300,
    lidarPpsWarn: 300,
    lidarPpsCrit: 120,
    speedWarn: 25,
    speedCrit: 35,
    canErrorWarn: 10,
    canErrorCrit: 25,
    startTime: null,
    endTime: null,
    isActive: false,
    updatedBy: "dispatcher.alex@coreguard.io",
    updatedAt: "2026-03-01 09:00:00",
  },
];
